---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    prometheus: main
spec:
  endpoints:
    - port: web
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus